<a href="https://colab.research.google.com/github/toche7/fuzzyMICMAC/blob/main/Reach_Matrix_Computation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def ssim_to_initial_reachability(ssim):
    n = len(ssim)
    initial_reachability = [[0]*n for _ in range(n)]

    for i in range(n):
        for j in range(n):
            if ssim[i][j] == 'V':
                initial_reachability[i][j] = 1
            elif ssim[i][j] == 'A':
                initial_reachability[j][i] = 1
            elif ssim[i][j] == 'X':
                initial_reachability[i][j] = 1
                initial_reachability[j][i] = 1

    return initial_reachability

# Example
ssim = [
    ['O', 'V', 'X', 'O'],
    ['A', 'O', 'V', 'X'],
    ['X', 'A', 'O', 'V'],
    ['O', 'X', 'A', 'O']
]

initial_reachability_matrix = ssim_to_initial_reachability(ssim)

for row in initial_reachability_matrix:
    print(row)


[0, 1, 1, 0]
[0, 0, 1, 1]
[1, 0, 0, 1]
[0, 1, 0, 0]


In [ ]:
def warshall_algorithm(adj_matrix):
    # Number of vertices in the graph
    n = len(adj_matrix)
    import copy

    # Initialize the reachability matrix with the given adjacency matrix
    reachability_matrix = [[0 for j in range(n)] for i in range(n)]
    #init_matrix = [[0 for j in range(n)] for i in range(n)]
    for i in range(n):
        for j in range(n):
            if i == j or adj_matrix[i][j] != 0:
                # If i == j or there's a direct edge from i to j
                reachability_matrix[i][j] = 1

    init_matrix = copy.deepcopy(reachability_matrix)
#    print('init_matrix =',init_matrix)
    # Apply Warshall's algorithm to compute the transitive closure
    for k in range(n):
        for i in range(n):
            for j in range(n):
                reachability_matrix[i][j] = reachability_matrix[i][j] or (reachability_matrix[i][k] and reachability_matrix[k][j])
#    print('init_matrix =',init_matrix)
    return reachability_matrix, init_matrix

# Example Usage:
graph = [
    [0, 1, 0],
    [0, 0, 1],
    [0, 0, 0]
]

aaa = warshall_algorithm(graph)
aaa


([[1, 1, 1], [0, 1, 1], [0, 0, 1]], [[1, 1, 0], [0, 1, 1], [0, 0, 1]])

In [ ]:
graph2 = [
[1 , 1 , 1 , 1 , 0 , 1 , 1 , 1 , 0 , 1],
[1 , 1 , 0 , 0 , 0 , 1 , 1 , 1 , 0 , 1],
[0 , 0 , 1 , 0 , 0 , 1 , 0 , 0 , 0 , 0],
[0 , 0 , 0 , 1 , 1 , 1 , 0 , 1 , 0 , 0],
[0 , 0 , 0 , 1 , 1 , 0 , 0 , 0 , 0 , 0],
[0 , 0 , 0 , 0 , 0 , 1 , 0 , 1 , 1 , 0],
[0 , 0 , 0 , 1 , 0 , 1 , 1 , 0 , 1 , 0],
[0 , 0 , 0 , 0 , 0 , 0 , 0 , 1 , 0 , 0],
[0 , 0 , 0 , 1 , 0 , 1 , 0 , 0 , 1 , 0],
[0 , 0 , 1 , 0 , 0 , 1 , 1 , 0 , 1 , 1]]

reachability_matrix = warshall_algorithm(graph2)
for row in reachability_matrix[0]:
    print(row)

print('aaa')
for row in reachability_matrix[1]:
    print(row)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 1, 1, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 1, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 1, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 1, 1, 1, 0, 1, 1, 0]
[0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 1, 1, 1, 0, 1, 1, 0]
[0, 0, 1, 1, 1, 1, 1, 1, 1, 1]
aaa
[1, 1, 1, 1, 0, 1, 1, 1, 0, 1]
[1, 1, 0, 0, 0, 1, 1, 1, 0, 1]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[0, 0, 0, 1, 1, 1, 0, 1, 0, 0]
[0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 1, 1, 0]
[0, 0, 0, 1, 0, 1, 1, 0, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 1, 0, 1, 0, 0, 1, 0]
[0, 0, 1, 0, 0, 1, 1, 0, 1, 1]


In [ ]:
def text_matrix_fn(adj_matrix):
  reachability_matrix, init_matrix = warshall_algorithm(adj_matrix)
  n = len(reachability_matrix)
  text_matrix = [[0 for j in range(n)] for i in range(n)]
  for i in range(n):
    for j in range(n):
      if reachability_matrix[i][j] == init_matrix[i][j]:
        text_matrix[i][j] = str(reachability_matrix[i][j])
      else:
        text_matrix[i][j] = '1*'

  return text_matrix



In [ ]:
for row in text_matrix_fn(graph2):
  print(row)

['1', '1', '1', '1', '1*', '1', '1', '1', '1*', '1']
['1', '1', '1*', '1*', '1*', '1', '1', '1', '1*', '1']
['0', '0', '1', '1*', '1*', '1', '0', '1*', '1*', '0']
['0', '0', '0', '1', '1', '1', '0', '1', '1*', '0']
['0', '0', '0', '1', '1', '1*', '0', '1*', '1*', '0']
['0', '0', '0', '1*', '1*', '1', '0', '1', '1', '0']
['0', '0', '0', '1', '1*', '1', '1', '1*', '1', '0']
['0', '0', '0', '0', '0', '0', '0', '1', '0', '0']
['0', '0', '0', '1', '1*', '1', '0', '1*', '1', '0']
['0', '0', '1', '1*', '1*', '1', '1', '1*', '1', '1']


In [ ]:
import numpy as np
reachMatrix = np.array(warshall_algorithm(graph2)[0])
reachMatrix

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
reachMatrix.sum(axis = 1)

array([10, 10,  6,  5,  5,  5,  6,  1,  5,  8])

In [ ]:
reachMatrix.sum(axis = 0)

array([ 2,  2,  4,  9,  9,  9,  4, 10,  9,  3])

In [ ]:
def partition_reachability_matrix(matrix):
    n = len(matrix)
    levels = []

    # Copy the matrix to avoid modifying the original
    temp_matrix = [row[:] for row in matrix]

    level_num = 1  # To keep track of the level number

    print(f"\n===Factor:  [reachability_set],[ Antecedent Set], [Intersection]===")

    while any(cell == 1 for row in temp_matrix for cell in row):  # Continue until the matrix has any 1s left
        current_level = set()

        print(f"\n--------------- Processing Level {level_num} ---------------")
        for i in range(n):
            # If row is already all zeros, skip
            if sum(temp_matrix[i]) == 0:
                continue

            # Find reachability set for element i
            reachability_set = {j for j, x in enumerate(temp_matrix[i]) if x == 1}

            # Find antecedent set for element i
            antecedent_set = {j for j in range(n) if temp_matrix[j][i] == 1}

            # Intersection of the two sets
            intersection = reachability_set.intersection(antecedent_set)

            # Print for clarity
            print(f"F{i+1}:,{[x+1 for x in reachability_set]}, {[x+1 for x in antecedent_set]}, {[x+1 for x in intersection]}")
            #print(f"  Reachability Set: {[x+1 for x in reachability_set]}   Antecedent Set: {[x+1 for x in antecedent_set]} Intersection: {[x+1 for x in intersection]}")
            #print(f"  Antecedent Set: {[x+1 for x in antecedent_set]}")
            #print(f"  Intersection: {[x+1 for x in intersection]}")

            # If the intersection is the same as reachability set, add to current level
            if intersection == reachability_set:
                current_level.add(i)

        # Remove current level elements from the matrix for the next iteration
        for i in current_level:
            for j in range(n):
                temp_matrix[i][j] = 0
                temp_matrix[j][i] = 0

        levels.append(current_level)
        level_num += 1
    print(f"\n=============================================")

    return levels

# Using the previously created final_reachability_matrix as an example
matrix = [
    [1, 1, 1, 0],
    [0, 1, 1, 1],
    [0, 0, 1, 1],
    [0, 0, 0, 1]
]

levels = partition_reachability_matrix(matrix)

print("\nFinal Levels:")
for idx, level in enumerate(levels, 1):
    print(f"Level {idx}:", [item + 1 for item in level])  # +1 for 1-based indexing



===Factor:  [reachability_set],[ Antecedent Set], [Intersection]===

--------------- Processing Level 1 ---------------
F1:,[1, 2, 3], [1], [1]
F2:,[2, 3, 4], [1, 2], [2]
F3:,[3, 4], [1, 2, 3], [3]
F4:,[4], [2, 3, 4], [4]

--------------- Processing Level 2 ---------------
F1:,[1, 2, 3], [1], [1]
F2:,[2, 3], [1, 2], [2]
F3:,[3], [1, 2, 3], [3]

--------------- Processing Level 3 ---------------
F1:,[1, 2], [1], [1]
F2:,[2], [1, 2], [2]

--------------- Processing Level 4 ---------------
F1:,[1], [1], [1]


Final Levels:
Level 1: [4]
Level 2: [3]
Level 3: [2]
Level 4: [1]


In [ ]:
levels = partition_reachability_matrix(warshall_algorithm(graph2)[0])

for level in levels:
    print("Level :", [item + 1 for item in level])  # +1 for 1-based indexin


===Factor:  [reachability_set],[ Antecedent Set], [Intersection]===

--------------- Processing Level 1 ---------------
F1:,[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2], [1, 2]
F2:,[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2], [1, 2]
F3:,[3, 4, 5, 6, 8, 9], [1, 2, 3, 10], [3]
F4:,[4, 5, 6, 8, 9], [1, 2, 3, 4, 5, 6, 7, 9, 10], [9, 4, 5, 6]
F5:,[4, 5, 6, 8, 9], [1, 2, 3, 4, 5, 6, 7, 9, 10], [9, 4, 5, 6]
F6:,[4, 5, 6, 8, 9], [1, 2, 3, 4, 5, 6, 7, 9, 10], [9, 4, 5, 6]
F7:,[4, 5, 6, 7, 8, 9], [1, 2, 7, 10], [7]
F8:,[8], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [8]
F9:,[4, 5, 6, 8, 9], [1, 2, 3, 4, 5, 6, 7, 9, 10], [9, 4, 5, 6]
F10:,[3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 10], [10]

--------------- Processing Level 2 ---------------
F1:,[1, 2, 3, 4, 5, 6, 7, 9, 10], [1, 2], [1, 2]
F2:,[1, 2, 3, 4, 5, 6, 7, 9, 10], [1, 2], [1, 2]
F3:,[3, 4, 5, 6, 9], [1, 2, 3, 10], [3]
F4:,[9, 4, 5, 6], [1, 2, 3, 4, 5, 6, 7, 9, 10], [9, 4, 5, 6]
F5:,[9, 4, 5, 6], [1, 2, 3, 4, 5, 6, 7, 9, 10], [9, 4, 5, 6]
F6:,[9, 4, 5, 6], [1, 2, 3