<a href="https://colab.research.google.com/github/toche7/fuzzyMICMAC/blob/main/TransitiveMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import genfromtxt

matrix_data = genfromtxt('./sample_data/beef.csv', delimiter=',',dtype=float)
#matrix_data[0][0] = 1 # BOM correction (invalid first byte)
data = (matrix_data > 0)
data1 = data.astype(int)

def warshall(a):
    assert (len(row) == len(a) for row in a)
    n = len(a)
    for k in range(n):
        for i in range(n):
            for j in range(n):
                a[i][j] = int(a[i][j]) or (int(a[i][k]) and int(a[k][j]))
    return a

reachability = warshall(data1.copy())

#print(matrix_data)

print("Input data:")
print(data1)
print("Trasitive matrix:")
print(reachability)


Input data:
[[1 1 0 1 0 0 0 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 1 0 0 0 0 0]]
Trasitive matrix:
[[1 1 0 1 0 1 0 0 1 0 1]
 [1 1 0 1 0 1 0 0 1 0 1]
 [1 1 0 1 0 1 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 0 0 0 0]
 [1 1 0 1 0 1 0 0 1 0 1]
 [0 0 0 1 1 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [1 1 0 1 0 1 0 0 1 0 1]
 [1 1 0 1 0 1 0 0 1 0 1]
 [1 1 0 1 0 1 0 0 1 0 1]]


In [ ]:
matrix_data

array([[1. , 0.9, 0. , 0.7, 0. , 0. , 0. , 0. , 0.7, 0. , 0.5],
       [0.9, 0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.3, 0. , 0.5, 0. , 0. , 0. , 0.7, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.1, 0. , 0. , 0.1, 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0.7],
       [0. , 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0. , 0. , 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.7, 0. , 0. , 0.9, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0. , 0. , 0.3, 0. , 0.7, 0. , 0. , 0. , 0. , 0. ]])

In [ ]:
data = (matrix_data > 0)
data.astype(int)


array([[1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0]])